"""like

Revision ID: 604fefcb31bb
Revises: b8f1738d90c9
Create Date: 2022-05-03 21:32:57.823021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604fefcb31bb'
down_revision = 'b8f1738d90c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('likes', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'likes')
    # ### end Alembic commands ###
