"""folowing_count

Revision ID: b249e061b3bb
Revises: ba4f6802b398
Create Date: 2022-05-16 11:33:59.479362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b249e061b3bb'
down_revision = 'ba4f6802b398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('following_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('Users', sa.Column('followers_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'followers_count')
    op.drop_column('Users', 'following_count')
    # ### end Alembic commands ###
