"""p_date

Revision ID: b8f1738d90c9
Revises: e373b479cc96
Create Date: 2022-05-03 20:14:42.999910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f1738d90c9'
down_revision = 'e373b479cc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('publication_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'publication_date')
    # ### end Alembic commands ###
