"""base

Revision ID: df7e636013e9
Revises: 
Create Date: 2022-05-01 13:57:09.781554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df7e636013e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=False),
    sa.Column('profile_photo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index(op.f('ix_Users_login'), 'Users', ['login'], unique=True)
    op.create_table('Readership',
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reader_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Readership')
    op.drop_index(op.f('ix_Users_login'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
